#!/bin/bash

step=5

filepath="/sys/class/backlight/intel_backlight"
max_brightness=$(cat $filepath/max_brightness)
brightness=$(cat $filepath/brightness)
brightness_perc=$(( brightness * 100 / max_brightness ))

if [ -z "$1" ]; then
  echo "$brightness_perc"
  exit 0
fi

if [ "inc" = "$1" ]; then
  brightness_perc=$(( brightness_perc + step > 100
                      ? 100
                      : brightness_perc + step))
elif [ "dec" = "$1" ]; then
  brightness_perc=$(( brightness_perc - step < 0
                      ? 0
                      : brightness_perc - step))
fi

brightness=$(( brightness_perc * max_brightness / 100 ))

echo $brightness > $filepath/brightness
